- name: configure apache with passenger snippet
  shell: source /etc/profile.d/rvm.sh && /usr/local/rvm/bin/rvm default && passenger-install-apache2-module --snippet>/etc/httpd/conf.modules.d/100-passenger_conf
         chdir={{redmine_app_dir}}
         executable="/bin/bash"
  when: redmine_app_dir_stat.stat.isdir is not defined

- name: define Passenger user as redmine 
  lineinfile: dest=/etc/httpd/conf.modules.d/100-passenger_conf
              line="PassengerUser redmine"
  when: redmine_app_dir_stat.stat.isdir is not defined
- name: define Passenger group as redmine 
  lineinfile: dest=/etc/httpd/conf.modules.d/100-passenger_conf
              line="PassengerGroup redmine"
  when: redmine_app_dir_stat.stat.isdir is not defined

