#################################################################################
# get (clone) redmine from github
#################################################################################
- name: Clone redmine from git
  git: repo=https://github.com/redmine/redmine.git
      dest={{redmine_app_dir}}
      version={{redmine_version}}
  when: redmine_app_dir_stat.stat.isdir is not defined
#################################################################################
# configure redmine database
#################################################################################
- name: Apply template to set the database config
  template: src=database.yml.jinja2 dest={{redmine_app_dir}}/config/database.yml
  when: redmine_app_dir_stat.stat.isdir is not defined
