---
#################################################################################
# add redmine user
#################################################################################
- name: add sys user redmine (will run redmine)
  user: name={{redmine_user}}
        system=yes
        state=present
        home={{redmine_app_dir}}
        createhome=no
- include: check_already_installed.yml
- include: install_packages.yml
- include: conf_redmine.yml
- include: conf_ruby_env.yml
- include: conf_apache.yml
- include: security.yml
